# Generated by Django 4.0.2 on 2022-02-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0007_meal_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='menu',
            field=models.TextField(),
        ),
    ]
