# Generated by Django 4.0.2 on 2022-02-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0011_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='spicy',
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Process', 'Process'), ('closed', 'Closed')], default='new', max_length=100),
        ),
    ]
