# Generated by Django 4.0.2 on 2022-02-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0018_shopcart_checkout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'managed': True, 'verbose_name': 'Checkout', 'verbose_name_plural': 'Checkouts'},
        ),
        migrations.AlterModelOptions(
            name='shopcart',
            options={'managed': True, 'verbose_name': 'Shopcart', 'verbose_name_plural': 'Shopcarts'},
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='spicy',
        ),
        migrations.AddField(
            model_name='checkout',
            name='admin_remark',
            field=models.CharField(default='new', max_length=250),
        ),
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered')], default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='product_name',
            field=models.CharField(default='o', max_length=100),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='total',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='checkout',
            table='checkout',
        ),
        migrations.AlterModelTable(
            name='shopcart',
            table='shopcart',
        ),
    ]
