# Generated by Django 4.0.2 on 2022-03-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='cart_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
