# Generated by Django 4.0.2 on 2022-03-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_uprofile_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
