# Generated by Django 4.0.2 on 2022-03-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_uprofile_city_alter_uprofile_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='cart_code',
            field=models.AutoField(default=101, primary_key=True, serialize=False),
        ),
    ]
