# Generated by Django 4.0.2 on 2022-03-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_uprofile_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='cart_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
