# Generated by Django 4.0.2 on 2022-02-24 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodie', '0021_remove_checkout_shopcart_delete_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('spicy', models.CharField(default='new', max_length=50)),
                ('product_name', models.CharField(default='o', max_length=100)),
                ('total', models.IntegerField(default=1)),
                ('order_no', models.CharField(max_length=50)),
                ('item_paid', models.BooleanField(default=False)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopcart',
                'verbose_name_plural': 'Shopcarts',
                'db_table': 'shopcart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordr_no', models.CharField(max_length=50)),
                ('itm_paid', models.BooleanField(default=False)),
                ('total', models.FloatField()),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('name_on_card', models.CharField(max_length=200)),
                ('card_number', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered')], default='new', max_length=50)),
                ('admin_remark', models.CharField(default='new', max_length=250)),
                ('shopcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopcart.shopcart')),
            ],
            options={
                'verbose_name': 'Checkout',
                'verbose_name_plural': 'Checkouts',
                'db_table': 'checkout',
                'managed': True,
            },
        ),
    ]
