# Generated by Django 4.0.2 on 2022-02-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='spicy',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='now_spicy',
            field=models.CharField(default='o', max_length=50),
        ),
    ]
