# Generated by Django 4.0.2 on 2022-03-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0004_paidorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidorder',
            name='cart_no',
            field=models.CharField(blank=True, default='r', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='paidorder',
            name='name_on_crd',
            field=models.CharField(default='r', max_length=200),
        ),
        migrations.AddField(
            model_name='paidorder',
            name='paid_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paidorder',
            name='payment_code',
            field=models.CharField(default='o', max_length=50),
        ),
        migrations.AddField(
            model_name='paidorder',
            name='total',
            field=models.FloatField(default=1.1),
        ),
    ]
