# Generated by Django 4.0.2 on 2022-03-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0005_paidorder_cart_no_paidorder_name_on_crd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidorder',
            name='cart_no',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='paidorder',
            name='name_on_crd',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paidorder',
            name='payment_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paidorder',
            name='total',
            field=models.FloatField(),
        ),
    ]
