# Generated by Django 4.0.2 on 2022-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0009_ship_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='name_on_crd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
