# Generated by Django 4.0.2 on 2022-03-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0021_remove_checkout_shopcart_delete_contact_and_more'),
        ('shopcart', '0010_alter_ship_address_alter_ship_name_on_crd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodie.meal'),
        ),
    ]
