# Generated by Django 4.0.2 on 2022-03-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0012_alter_ship_ordr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='ordr_no',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
