# Generated by Django 4.0.2 on 2022-03-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0013_alter_ship_ordr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
